# In combination with fused_mlp_small:
# - works well for LAC DEM
# - gives bumpy LDEM

otype: HashGrid
n_levels: 6
n_features_per_level: 2
log2_hashmap_size: 18
base_resolution: 16
per_level_scale: 1.5
interpolation: Linear